latest: "2"
contentOrientation: relative
extendBaseTo: /v2
forceParent:
  customerMyBalance: ""
  customerMyBillingHistory: ""
  customerMyInvoice: ""
  monitoringMetricDropletBandwidth: ""
  monitoringMetricDropletCPU: ""
  monitoringMetricDropletFilesystemFree: ""
  monitoringMetricDropletFilesystemSize: ""
  monitoringMetricDropletLoad1: ""
  monitoringMetricDropletLoad15: ""
  monitoringMetricDropletLoad5: ""
  monitoringMetricDropletMemoryAvailable: ""
  monitoringMetricDropletMemoryCached: ""
  monitoringMetricDropletMemoryFree: ""
  monitoringMetricDropletMemoryTotal: ""
  kubernetesCluster: ""
forceItemPaths:
  "/registry/{registry_name}/garbage-collection": true
relativeContentPaths:
  - ^/customers/my/.*
forceMethodOpName:
  "/droplets/actions":
    post: "createForTag"
  "/volumes/actions":
    post: "createByName"
wrapsItems: true