latest: "2"
contentOrientation: relative
extendBaseTo: /v2
forceParent:
  customerMyBalance: ""
  customerMyBillingHistory: ""
  customerMyInvoice: ""
forceItemPaths:
  "/registry/{registry_name}/garbage-collection": true
relativeContentPaths:
  - ^/customers/my/.*
forceMethodOpName:
  "/droplets/actions":
    post: "createForTag"
  "/volumes/actions":
    post: "createByName"